name: "Run CI"

on: pull_request

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: prefix-dev/setup-pixi@v0.8.1
        with:
            pixi-version: v0.40.2
            cache: true
            auth-host: prefix.dev
            auth-token: ${{ secrets.PREFIX_DEV_TOKEN }}
      - run: pixi run test

