name: long_run

on:
    pull_request:
    workflow_dispatch:
    schedule:
        - cron: '0 0 * * *'

jobs:
    check_new_commit:
        runs-on: ubuntu-latest
        outputs:
          nb_commits: ${{ steps.new_commits.outputs.nb_commits }}
        steps:
          - uses: actions/checkout@v3

          - id: new_commits
            run: echo "nb_commits=$(git log --oneline --since '24 hours ago' | wc -l)" >> $GITHUB_OUTPUT

    clang-tidy-check:
        needs: check_new_commit
        if: needs.check_new_commit.outputs.nb_commits > 0
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - uses: prefix-dev/setup-pixi@v0.8.1
              with:
                pixi-version: v0.40.2
                cache: true

            - name: Configure
              shell: pixi run bash {0}
              run: |
                cmake . -Bbuild -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_BUILD_TYPE=Debug -DBUILD_EXAMPLES=ON
                pip install compdb
                compdb -p build list > compile_commands.json

            - name: run clang-tidy
              shell: pixi run bash {0}
              run: |
                run-clang-tidy
