name: long_run

on:
    pull_request:
    workflow_dispatch:
    schedule:
        - cron: '0 0 * * *'

jobs:
    check_new_commit:
        runs-on: ubuntu-latest
        outputs:
          nb_commits: ${{ steps.new_commits.outputs.nb_commits }}
        steps:
          - uses: actions/checkout@v3

          - id: new_commits
            run: echo "nb_commits=$(git log --oneline --since '24 hours ago' | wc -l)" >> $GITHUB_OUTPUT
